-- CREATE USER PETCAB IDENTIFIED BY PETCAB;
-- GRANT RESOURCE, CONNECT TO PETCAB;
 
 
-- drop table REVIEW_REPLY CASCADE CONSTRAINTS;
 --================================================================
 
--?ç∞?†§?ã§Ï§ÑÍ∞ú ?åå?ù¥?Ñê?îÑÎ°úÏ†ù?ä∏
CREATE TABLE MEMBER (
	USER_NO	NUMBER	NOT NULL,
	USER_NAME	VARCHAR2(20)	NOT NULL,
	USER_ID	VARCHAR2(20)	NOT NULL,
	USER_PWD	VARCHAR2(100)	NOT NULL,
	POSTCODE	NUMBER	NOT NULL,
	ADDRESS	VARCHAR2(1000)	NOT NULL,
	PHONE	VARCHAR2(20)	NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	USER_TYPE	VARCHAR2(20) DEFAULT 'ROLE_MEMBER'
);

CREATE TABLE REVIEW (
	REVIEW_NO	NUMBER	NOT NULL,
	CALL_TYPE	VARCHAR2(20)	NOT NULL,
	GROUP_NO	NUMBER	NOT NULL,
	GROUP_SEQ	NUMBER	NULL,
	DEPTH	NUMBER	NULL,
	TITLE	VARCHAR2(200)	NOT NULL,
	CONTENT	VARCHAR2(2000)	NOT NULL,
	STAR_NO	NUMBER NOT NULL,
	POST_DATE	DATE DEFAULT SYSDATE,
	EDIT_DATE	DATE DEFAULT SYSDATE,
	VIEW_NO	NUMBER NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	USER_NO	NUMBER	NOT NULL,
	CALL_NO	NUMBER	NOT NULL
);

CREATE TABLE DOG (
	ANIMAL_NO	VARCHAR2(100)	NOT NULL,
	DOG_NAME	VARCHAR2(50)	NOT NULL,
	DOG_TYPE	VARCHAR2(50)	NOT NULL,
	AGE	NUMBER	NULL,
	VACC	VARCHAR2(100)	NULL,
	DISORDER	VARCHAR2(100)	NULL,
	OTHER	VARCHAR2(1000)	NULL,
	IMAGE_ORI	VARCHAR2(2000)	NULL,
	IMAGE_RE	VARCHAR2(2000)	NULL,
	USER_NO	NUMBER	NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

CREATE TABLE PARTNER (
	USER_NO	NUMBER	NOT NULL,
	PARTNER_NAME	VARCHAR2(100)	NOT NULL,
	PARTNER_TYPE	VARCHAR2(20)	NOT NULL,
	LOCATION	VARCHAR2(1000)	NOT NULL,
	PHONE	VARCHAR2(20)	NOT NULL,
	OPEN_TIME	VARCHAR2(500)	NOT NULL,
	IMAGE_ORI	VARCHAR2(2000)	NULL,
	IMAGE_RE	VARCHAR2(2000)	NULL,
	ABOUT	VARCHAR2(3000)	NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

CREATE TABLE GEN_CALL (
	CALL_NO	NUMBER	NOT NULL,
	TIME	DATE	NOT NULL,
	FROM_WHERE	VARCHAR2(500)	NOT NULL,
	TO_WHERE	VARCHAR2(500)	NOT NULL,
	WITH_OWNER	VARCHAR2(3)	NOT NULL,
	TO_DRIVER	VARCHAR2(1000)	NOT NULL,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	CALL_TYPE	NUMBER	NOT NULL,
	USER_NO	NUMBER	NOT NULL,
	ANIMAL_NO_A	VARCHAR2(100)	NOT NULL,
	ANIMAL_NO_B	VARCHAR2(100)	NULL,
	ANIMAL_NO_C	VARCHAR2(100)	NULL,
	MERCHANT_UID	VARCHAR2(1000) NULL
);

CREATE TABLE REVIEW_REPLY (
	REPLY_NO	NUMBER	NOT NULL,
	GROUP_NO	NUMBER	NOT NULL,
	GROUP_SEQ	NUMBER	NULL,
	DEPTH	NUMBER	NULL,
	CONTENT	VARCHAR2(1000)	NULL,
	POST_DATE	DATE DEFAULT SYSDATE,
	EDIT_DATE	DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(3) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	USER_NO	NUMBER	NOT NULL,
	REVIEW_NO	NUMBER	NOT NULL
);

CREATE TABLE QUES (
	QUES_NO	NUMBER	NOT NULL,
	TITLE	VARCHAR2(200)	NOT NULL,
	CONTENT	VARCHAR2(2000)	NOT NULL,
	POST_DATE	DATE DEFAULT SYSDATE,
	EDIT_DATE	DATE DEFAULT SYSDATE,
	VIEW_NO	NUMBER NULL,
	QUES_TYPE	VARCHAR2(50)	NOT NULL,
	QUES_PWD	NUMBER	NULL,
	GROUP_NO	NUMBER	NOT NULL,
	GROUP_SEQ	NUMBER	NULL,
	DEPTH	NUMBER	NULL,
	USER_NO	NUMBER	NOT NULL
);

CREATE TABLE DRIVER (
	USER_NO	NUMBER	NOT NULL,
	CAR_TYPE	VARCHAR2(20)	NULL,
	CAR_NO	VARCHAR2(50)	NULL,
	ABOUT	VARCHAR2(2000)	NULL,
	IMAGE_ORI	VARCHAR2(2000)	NULL,
	IMAGE_RE	VARCHAR2(2000)	NULL
);

CREATE TABLE QUES_REPLY (
	QUES_NO	NUMBER	NOT NULL,
	CONTENT	VARCHAR2(2000)	NOT NULL,
	POST_DATE	DATE DEFAULT SYSDATE,
	EDIT_DATE	DATE DEFAULT SYSDATE,
	USER_NO	NUMBER	NOT NULL
);

CREATE TABLE EMERG_CALL (
	CALL_NO	NUMBER	NOT NULL,
	TO_PARTNER	VARCHAR2(1000)	NULL,
	TO_REJECT	VARCHAR2(100)	NULL,
	USER_NO	NUMBER	NOT NULL
);

CREATE TABLE PAYMENT (
	MERCHANT_UID	VARCHAR2(1000)	NOT NULL,
	PG	VARCHAR2(100)	NOT NULL,
	PAY_METHOD	VARCHAR2(100)	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	AMOUNT	NUMBER	NOT NULL,
	IMP_UID	VARCHAR2(1000)	NOT NULL,
	PAID_AMOUNT	NUMBER	NOT NULL,
	APPLY_NUM	VARCHAR2(1000)	NOT NULL,
	SUCCESS	VARCHAR2(100)	NOT NULL,
	STATUS	VARCHAR2(100)	NOT NULL,
	PG_PROVIDER	VARCHAR2(100)	NOT NULL,
	PG_TID	VARCHAR2(100)	NOT NULL,
	PAID_AT	NUMBER	NOT NULL,
	RECEIPT_URL	VARCHAR2(100)	NOT NULL,
	VBANK_NUM	VARCHAR2(100)	NULL,
	VBANK_NAME	VARCHAR2(100)	NULL,
	VBANK_HOLDER	VARCHAR2(100)	NULL,
	VBANK_DATE	NUMBER	NULL,
	USER_NO	NUMBER	NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	USER_NO
);

ALTER TABLE REVIEW ADD CONSTRAINT PK_REVIEW PRIMARY KEY (
	REVIEW_NO
);

ALTER TABLE DOG ADD CONSTRAINT PK_DOG PRIMARY KEY (
	ANIMAL_NO
);

ALTER TABLE PARTNER ADD CONSTRAINT PK_PARTNER PRIMARY KEY (
	USER_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT PK_GEN_CALL PRIMARY KEY (
	CALL_NO
);

ALTER TABLE REVIEW_REPLY ADD CONSTRAINT PK_REVIEW_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE QUES ADD CONSTRAINT PK_QUES PRIMARY KEY (
	QUES_NO
);

ALTER TABLE DRIVER ADD CONSTRAINT PK_DRIVER PRIMARY KEY (
	USER_NO
);

ALTER TABLE QUES_REPLY ADD CONSTRAINT PK_QUES_REPLY PRIMARY KEY (
	QUES_NO
);

ALTER TABLE EMERG_CALL ADD CONSTRAINT PK_EMERG_CALL PRIMARY KEY (
	CALL_NO
);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
	MERCHANT_UID
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_MEMBER_TO_REVIEW_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE REVIEW ADD CONSTRAINT FK_GEN_CALL_TO_REVIEW_1 FOREIGN KEY (
	CALL_NO
)
REFERENCES GEN_CALL (
	CALL_NO
);

ALTER TABLE DOG ADD CONSTRAINT FK_MEMBER_TO_DOG_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE PARTNER ADD CONSTRAINT FK_MEMBER_TO_PARTNER_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT FK_DRIVER_TO_GEN_CALL_1 FOREIGN KEY (
	USER_NO
)
REFERENCES DRIVER (
	USER_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT FK_DOG_TO_GEN_CALL_1 FOREIGN KEY (
	ANIMAL_NO_A
)
REFERENCES DOG (
	ANIMAL_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT FK_DOG_TO_GEN_CALL_2 FOREIGN KEY (
	ANIMAL_NO_B
)
REFERENCES DOG (
	ANIMAL_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT FK_DOG_TO_GEN_CALL_3 FOREIGN KEY (
	ANIMAL_NO_C
)
REFERENCES DOG (
	ANIMAL_NO
);

ALTER TABLE GEN_CALL ADD CONSTRAINT FK_PAYMENT_TO_GEN_CALL_1 FOREIGN KEY (
	MERCHANT_UID
)
REFERENCES PAYMENT (
	MERCHANT_UID
);

ALTER TABLE REVIEW_REPLY ADD CONSTRAINT FK_MEMBER_TO_REVIEW_REPLY_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE REVIEW_REPLY ADD CONSTRAINT FK_REVIEW_TO_REVIEW_REPLY_1 FOREIGN KEY (
	REVIEW_NO
)
REFERENCES REVIEW (
	REVIEW_NO
);

ALTER TABLE QUES ADD CONSTRAINT FK_MEMBER_TO_QUES_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE DRIVER ADD CONSTRAINT FK_MEMBER_TO_DRIVER_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE QUES_REPLY ADD CONSTRAINT FK_QUES_TO_QUES_REPLY_1 FOREIGN KEY (
	QUES_NO
)
REFERENCES QUES (
	QUES_NO
);

ALTER TABLE QUES_REPLY ADD CONSTRAINT FK_MEMBER_TO_QUES_REPLY_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

ALTER TABLE EMERG_CALL ADD CONSTRAINT FK_GEN_CALL_TO_EMERG_CALL_1 FOREIGN KEY (
	CALL_NO
)
REFERENCES GEN_CALL (
	CALL_NO
);

ALTER TABLE EMERG_CALL ADD CONSTRAINT FK_PARTNER_TO_EMERG_CALL_1 FOREIGN KEY (
	USER_NO
)
REFERENCES PARTNER (
	USER_NO
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_MEMBER_TO_PAYMENT_1 FOREIGN KEY (
	USER_NO
)
REFERENCES MEMBER (
	USER_NO
);

CREATE SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_REVIEW_NO;
CREATE SEQUENCE SEQ_CALL_NO;
CREATE SEQUENCE SEQ_QUES_NO;
CREATE SEQUENCE SEQ_MERCHANT_UID;


COMMENT ON COLUMN MEMBER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN MEMBER.USER_NAME IS '?öå?õêÎ™?';
COMMENT ON COLUMN MEMBER.USER_ID IS '?öå?õê?ïÑ?ù¥?îî';
COMMENT ON COLUMN MEMBER.USER_PWD IS '?öå?õêÎπÑÎ?Î≤àÌò∏';
COMMENT ON COLUMN MEMBER.POSTCODE IS '?ö∞?é∏Î≤àÌò∏';
COMMENT ON COLUMN MEMBER.ADDRESS IS 'Ï£ºÏÜå';
COMMENT ON COLUMN MEMBER.PHONE IS '?†Ñ?ôîÎ≤àÌò∏';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '?öå?õêÍ∞??ûÖ?ùº';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '?†ïÎ≥¥Ïàò?†ï?ùº';
COMMENT ON COLUMN MEMBER.STATUS IS '?ÉÅ?ÉúÍ∞?(Y/N)';
COMMENT ON COLUMN MEMBER.USER_TYPE IS '?öå?õê???ûÖ';

COMMENT ON COLUMN DOG.ANIMAL_NO IS '?èôÎ¨ºÎ≤à?ò∏';
COMMENT ON COLUMN DOG.DOG_NAME IS '?ï†Í≤¨Ïù¥Î¶?';
COMMENT ON COLUMN DOG.DOG_TYPE IS 'Í≤¨Ï¢Ö';
COMMENT ON COLUMN DOG.AGE IS '?Çò?ù¥';
COMMENT ON COLUMN DOG.VACC IS '?òàÎ∞©Ï†ëÏ¢?';
COMMENT ON COLUMN DOG.DISORDER IS '?äπ?ù¥ÏßàÎ≥ë';
COMMENT ON COLUMN DOG.OTHER IS 'Í∏∞Ì??Ç¨?ï≠';
COMMENT ON COLUMN DOG.IMAGE_ORI IS '?õêÎ≥∏Ïù¥ÎØ∏Ï??ù¥Î¶?';
COMMENT ON COLUMN DOG.IMAGE_RE IS 'Î≥?Í≤ΩÏù¥ÎØ∏Ï??ù¥Î¶?';
COMMENT ON COLUMN DOG.USER_NO IS 'Í≤¨Ï£ºÎ≤àÌò∏';
COMMENT ON COLUMN DOG.ENROLL_DATE IS '?ì±Î°ùÏùº?ûê';
COMMENT ON COLUMN DOG.MODIFY_DATE IS '?àò?†ï?ùº?ûê';
COMMENT ON COLUMN DOG.STATUS IS '?ÉÅ?ÉúÍ∞?(Y/N)';

COMMENT ON COLUMN DRIVER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN DRIVER.CAR_TYPE IS 'Î≥¥Ïú†Ï∞®Ï¢Ö';
COMMENT ON COLUMN DRIVER.CAR_NO IS 'Ï∞®ÎüâÎ≤àÌò∏';
COMMENT ON COLUMN DRIVER.ABOUT IS '?ûêÍ∏∞ÏÜåÍ∞?';
COMMENT ON COLUMN DRIVER.IMAGE_ORI IS '?õêÎ≥∏Ïù¥ÎØ∏Ï??ù¥Î¶?';
COMMENT ON COLUMN DRIVER.IMAGE_RE IS 'Î≥?Í≤ΩÏù¥ÎØ∏Ï??ù¥Î¶?';

COMMENT ON COLUMN EMERG_CALL.CALL_NO IS '?òà?ïΩÎ≤àÌò∏';
COMMENT ON COLUMN EMERG_CALL.TO_PARTNER IS '?öîÏ≤??Ç¨?ï≠';
COMMENT ON COLUMN EMERG_CALL.TO_REJECT IS 'Í±∞Ï†à?Ç¨?ú†';
COMMENT ON COLUMN EMERG_CALL.USER_NO IS '?†ú?ú¥?óÖÏ≤¥Ìöå?õêÎ≤àÌò∏';

COMMENT ON COLUMN GEN_CALL.CALL_NO IS '?òà?ïΩÎ≤àÌò∏';
COMMENT ON COLUMN GEN_CALL.TIME IS '?òà?ïΩ?ãúÍ∞?';
COMMENT ON COLUMN GEN_CALL.FROM_WHERE IS 'Ï∂úÎ∞úÏß?';
COMMENT ON COLUMN GEN_CALL.TO_WHERE IS '?èÑÏ∞©Ï?';
COMMENT ON COLUMN GEN_CALL.WITH_OWNER IS 'Î≥¥Ìò∏?ûê?Éë?äπ?ó¨Î∂?';
COMMENT ON COLUMN GEN_CALL.TO_DRIVER IS '?ìú?ùº?ù¥Î≤ÑÏöîÏ≤??Ç¨?ï≠';
COMMENT ON COLUMN GEN_CALL.STATUS IS '?òà?ïΩ?ÉÅ?Éú';
COMMENT ON COLUMN GEN_CALL.CALL_TYPE IS '?òà?ïΩ???ûÖ';
COMMENT ON COLUMN GEN_CALL.USER_NO IS '?ìú?ùº?ù¥Î≤ÑÎ≤à?ò∏';
COMMENT ON COLUMN GEN_CALL.ANIMAL_NO_A IS '?èôÎ¨ºÎ≤à?ò∏_1';
COMMENT ON COLUMN GEN_CALL.ANIMAL_NO_B IS '?èôÎ¨ºÎ≤à?ò∏_2';
COMMENT ON COLUMN GEN_CALL.ANIMAL_NO_C IS '?èôÎ¨ºÎ≤à?ò∏_3';
COMMENT ON COLUMN GEN_CALL.MERCHANT_UID IS 'Í≥†Ïú†Ï£ºÎ¨∏Î≤àÌò∏';

COMMENT ON COLUMN PAYMENT.MERCHANT_UID IS 'Í≥†Ïú†Ï£ºÎ¨∏Î≤àÌò∏';
COMMENT ON COLUMN PAYMENT.PG IS 'PG?Ç¨';
COMMENT ON COLUMN PAYMENT.PAY_METHOD IS 'Í≤∞Ï†ú?àò?ã®';
COMMENT ON COLUMN PAYMENT.NAME IS 'Ï£ºÎ¨∏Î™?';
COMMENT ON COLUMN PAYMENT.AMOUNT IS 'Í≤∞Ï†ú?ï†Í∏àÏï°';
COMMENT ON COLUMN PAYMENT.IMP_UID IS '?ïÑ?ûÑ?è¨?ä∏Í±∞ÎûòÍ≥†Ïú†Î≤àÌò∏';
COMMENT ON COLUMN PAYMENT.PAID_AMOUNT IS 'Í≤∞Ï†úÍ∏àÏï°';
COMMENT ON COLUMN PAYMENT.APPLY_NUM IS 'Ïπ¥Îìú?Ç¨?äπ?ù∏Î≤àÌò∏';
COMMENT ON COLUMN PAYMENT.SUCCESS IS 'Í≤∞Ï†úÏ≤òÎ¶¨Í∞??Ñ±Í≥µÏ†Å?ù¥???äîÏß??ó¨Î∂?';
COMMENT ON COLUMN PAYMENT.STATUS IS 'Í≤∞Ï†ú?ÉÅ?Éú';
COMMENT ON COLUMN PAYMENT.PG_PROVIDER IS 'Í≤∞Ï†ú?äπ?ù∏/?ãú?èÑ?êúPG?Ç¨';
COMMENT ON COLUMN PAYMENT.PG_TID IS 'PG?Ç¨Í±∞ÎûòÍ≥†Ïú†Î≤àÌò∏';
COMMENT ON COLUMN PAYMENT.PAID_AT IS 'Í≤∞Ï†ú?äπ?ù∏?ãúÍ∞?';
COMMENT ON COLUMN PAYMENT.RECEIPT_URL IS 'Ïπ¥Îìú?Ç¨?äπ?ù∏Î≤àÌò∏';
COMMENT ON COLUMN PAYMENT.VBANK_NUM IS 'Í∞??ÉÅÍ≥ÑÏ¢å?ûÖÍ∏àÍ≥ÑÏ¢åÎ≤à?ò∏';
COMMENT ON COLUMN PAYMENT.VBANK_NAME IS 'Í∞??ÉÅÍ≥ÑÏ¢å???ñâÎ™?';
COMMENT ON COLUMN PAYMENT.VBANK_HOLDER IS 'Í∞??ÉÅÍ≥ÑÏ¢å?òàÍ∏àÏ£º';
COMMENT ON COLUMN PAYMENT.VBANK_DATE IS 'Í∞??ÉÅÍ≥ÑÏ¢å?ûÖÍ∏àÍ∏∞?ïú';
COMMENT ON COLUMN PAYMENT.USER_NO IS '?öå?õêÎ≤àÌò∏';

COMMENT ON COLUMN QUES.QUES_NO IS 'Î¨∏ÏùòÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN QUES.TITLE IS '?†úÎ™?';
COMMENT ON COLUMN QUES.CONTENT IS '?Ç¥?ö©';
COMMENT ON COLUMN QUES.POST_DATE IS '?ì±Î°ùÏùº?ûê';
COMMENT ON COLUMN QUES.EDIT_DATE IS '?àò?†ï?ùº?ûê';
COMMENT ON COLUMN QUES.VIEW_NO IS 'Ï°∞Ìöå?àò';
COMMENT ON COLUMN QUES.QUES_TYPE IS 'Î¨∏ÏùòÎ∂ÑÎ•ò';
COMMENT ON COLUMN QUES.QUES_PWD IS 'ÎπÑÎ?Î≤àÌò∏';
COMMENT ON COLUMN QUES.GROUP_NO IS 'Î¨∏ÏùòÍ∑∏Î£πÎ≤àÌò∏';
COMMENT ON COLUMN QUES.GROUP_SEQ IS 'Î¨∏ÏùòÍ∑∏Î¶Ö?àú?Ñú';
COMMENT ON COLUMN QUES.DEPTH IS '?ãµÍ∏?ÍπäÏù¥';
COMMENT ON COLUMN QUES.USER_NO IS '?öå?õêÎ≤àÌò∏';

COMMENT ON COLUMN QUES_REPLY.QUES_NO IS 'Î¨∏ÏùòÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN QUES_REPLY.CONTENT IS '?åìÍ∏??Ç¥?ö©';
COMMENT ON COLUMN QUES_REPLY.POST_DATE IS '?ì±Î°ùÏùº?ûê';
COMMENT ON COLUMN QUES_REPLY.EDIT_DATE IS '?àò?†ï?ùº?ûê';
COMMENT ON COLUMN QUES_REPLY.USER_NO IS '?öå?õêÎ≤àÌò∏';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS 'Î¶¨Î∑∞Î≤àÌò∏';
COMMENT ON COLUMN REVIEW.CALL_TYPE IS 'ÏΩúÏ¢ÖÎ•?';
COMMENT ON COLUMN REVIEW.GROUP_NO IS 'Î¶¨Î∑∞Í∑∏Î£πÎ≤àÌò∏';
COMMENT ON COLUMN REVIEW.GROUP_SEQ IS 'Î¶¨Î∑∞Í∑∏Î£π?àú?Ñú';
COMMENT ON COLUMN REVIEW.DEPTH IS '?ãµÍ∏?ÍπäÏù¥';
COMMENT ON COLUMN REVIEW.TITLE IS 'Î¶¨Î∑∞?†úÎ™?';
COMMENT ON COLUMN REVIEW.CONTENT IS '?Ç¥?ö©';
COMMENT ON COLUMN REVIEW.STAR_NO IS '?èâ?†ê';
COMMENT ON COLUMN REVIEW.POST_DATE IS '?ì±Î°ùÏùº?ûê';
COMMENT ON COLUMN REVIEW.EDIT_DATE IS '?àò?†ï?ùº?ûê';
COMMENT ON COLUMN REVIEW.VIEW_NO IS 'Ï°∞Ìöå?àò';
COMMENT ON COLUMN REVIEW.STATUS IS '?ÉÅ?Éú';
COMMENT ON COLUMN REVIEW.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN REVIEW.CALL_NO IS '?òà?ïΩÎ≤àÌò∏';

COMMENT ON COLUMN REVIEW_REPLY.REPLY_NO IS '?åìÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN REVIEW_REPLY.GROUP_NO IS '?åìÍ∏?Í∑∏Î£πÎ≤àÌò∏';
COMMENT ON COLUMN REVIEW_REPLY.GROUP_SEQ IS '?åìÍ∏?Í∑∏Î£π?àú?Ñú';
COMMENT ON COLUMN REVIEW_REPLY.DEPTH IS '?åìÍ∏?ÍπäÏù¥';
COMMENT ON COLUMN REVIEW_REPLY.CONTENT IS '?åìÍ∏??Ç¥?ö©';
COMMENT ON COLUMN REVIEW_REPLY.POST_DATE IS '?ì±Î°ùÏùº?ûê';
COMMENT ON COLUMN REVIEW_REPLY.EDIT_DATE IS '?àò?†ï?ùº?ûê';
COMMENT ON COLUMN REVIEW_REPLY.STATUS IS '?ÉÅ?Éú';
COMMENT ON COLUMN REVIEW_REPLY.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN REVIEW_REPLY.REVIEW_NO IS 'Î¶¨Î∑∞Î≤àÌò∏';

COMMENT ON COLUMN PARTNER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN PARTNER.PARTNER_NAME IS '?†ú?ú¥?óÖÏ≤¥Î™Ö';
COMMENT ON COLUMN PARTNER.PARTNER_TYPE IS '?óÖÏ¢?';
COMMENT ON COLUMN PARTNER.LOCATION IS '?úÑÏπ?';
COMMENT ON COLUMN PARTNER.PHONE IS '?†Ñ?ôîÎ≤àÌò∏';
COMMENT ON COLUMN PARTNER.OPEN_TIME IS '?ò§?îà?ãúÍ∞?';
COMMENT ON COLUMN PARTNER.IMAGE_ORI IS '?õêÎ≥∏Ïù¥ÎØ∏Ï??ù¥Î¶?';
COMMENT ON COLUMN PARTNER.IMAGE_RE IS 'Î≥?Í≤ΩÏù¥ÎØ∏Ï??ù¥Î¶?';
COMMENT ON COLUMN PARTNER.ABOUT IS '?†ú?ú¥?óÖÏ≤¥ÏÜåÍ∞?';
COMMENT ON COLUMN PARTNER.STATUS IS '?†ú?ú¥?ÉÅ?Éú(Y/N)';
--------------------------------------------------------------------------------
--?ã§?ãú?ïò?Ñ∏?ö© ^^

ALTER TABLE MEMBER ADD UNIQUE(USER_ID);
ALTER TABLE DRIVER ADD UNIQUE(CAR_NO);

ALTER TABLE REVIEW MODIFY GROUP_SEQ NULL;
ALTER TABLE REVIEW MODIFY DEPTH NULL;
ALTER TABLE REVIEW MODIFY POST_DATE DATE DEFAULT SYSDATE; 
ALTER TABLE REVIEW MODIFY EDIT_DATE DATE DEFAULT SYSDATE;
ALTER TABLE REVIEW MODIFY VIEW_NO NULL;

ALTER TABLE GEN_CALL MODIFY MERCHANT_UID NULL;

ALTER TABLE REVIEW_REPLY MODIFY GROUP_NO NOT NULL;
ALTER TABLE REVIEW_REPLY MODIFY POST_DATE DATE DEFAULT SYSDATE; 
ALTER TABLE REVIEW_REPLY MODIFY EDIT_DATE DATE DEFAULT SYSDATE;

ALTER TABLE QUES MODIFY EDIT_DATE DATE DEFAULT SYSDATE;
ALTER TABLE QUES MODIFY POST_DATE DATE DEFAULT SYSDATE;
ALTER TABLE QUES MODIFY VIEW_NO NULL;
ALTER TABLE QUES MODIFY GROUP_SEQ NULL;
ALTER TABLE QUES MODIFY DEPTH NULL;


ALTER TABLE QUES_REPLY MODIFY POST_DATE DATE DEFAULT SYSDATE; 
ALTER TABLE QUES_REPLY MODIFY EDIT_DATE DATE DEFAULT SYSDATE;

CREATE SEQUENCE SEQ_REPLY_GROUP_NO;
CREATE SEQUENCE SEQ_REVIEW_GROUP_NO;
CREATE SEQUENCE SEQ_QUES_GROUP_NO;

ALTER TABLE MEMBER MODIFY USER_PWD VARCHAR2(100);

--------------------------------------------------------------------------------
ALTER TABLE MEMBER MODIFY USER_TYPE VARCHAR2(20) DEFAULT 'ROLE_MEMBER';

--?èôÎ¨ºÎ≤à?ò∏?äî ?ãú???ä§Î°? ?àú?Ñú??Î°? Í∞??äî Í≤ÉÏù¥ ?ïÑ?ãå Í≥†Ïú†?ùò Î≤àÌò∏?ù¥Í∏∞Ïóê ?ãú???ä§ Î≤àÌò∏Î•? ?Ç≠?†ú?ï¥?ïº?ï®
--CREATE SEQUENCE SEQ_ANMAL_NO;
DROP SEQUENCE SEQ_ANMAL_NO;
--------------------------------------------------------------------------------

-----øπæ‡ ∞¸∑√ ƒı∏Æ √ﬂ∞° -----

-- øπæ‡Ω≈√ª varchar2 ¥√∏Æ±‚
alter table 
    GEN_CALL
modify 
(
   STATUS    varchar2(10)
);

alter table GEN_CALL modify MERCHANT_UID NULL;

alter table GEN_CALL modify TIME NULL; -- ?

--ALTER TABLE GEN_CALL MODIFY TIME DATE DEFAULT SYSDATE;

--ALTER TABLE GEN_CALL MODIFY TIME DEFAULT NULL;

ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI';

alter table GEN_CALL modify WITH_OWNER NULL;

-- æ÷∞ﬂ¡§∫∏µÓ∑œ ±∏«ˆ øœ∑· »ƒ NOT NULL∑Œ ∫Ø∞Ê « ø‰
alter table GEN_CALL modify ANIMAL_NO_A NULL;

-- ƒ›≈∏¿‘º±≈√ ±∏«ˆ øœ∑· »ƒ NOT NULL∑Œ ∫Ø∞Ê « ø‰
alter table GEN_CALL modify CALL_TYPE NULL;

-- µÂ∂Û¿Ãπˆ∏≈ƒ™ »ƒ ∞™¿Ã √ﬂ∞°µ«π«∑Œ NULL
alter table GEN_CALL modify USER_NO NULL;

--------------------------------------------------------------------------------

----- øπæ‡ ∞¸∑√ ƒı∏Æ ≈◊Ω∫∆Æ -----

--SELECT TO_DATE('2012-06-05', 'YYYY-MM-DD') FROM dual;
--SELECT TO_DATE('2021-04-02T19:00', "YYYY-MM-DD'T'HH:MI") FROM DUAL;

--------------------------------------------------------------------------------
